livros <- c("O Pequeno Príncipe", "Dom Quixote", "1984", "Orgulho e Preconceito", "O Hobbit")
print(paste("Primeiro livro:", livros[1]))
print(paste("Ultimo Livro:", livros[length(livros)]))
livros <- c("Harry Potter", livros)
print(livros)